#include <stdio.h>
#include <stdlib.h>
#include <string.h>
/* ================= ENUM ====*/
// TODO: Define an enum called ProgramType
// It should have:
// UNDERGRADUATE
// POSTGRADUATE
typedef enum {
UNDERGRADUATE,
POSTGRADUATE
} ProgramType;
/* ================= UNION ================= */
// TODO: Define a union called AcademicInfo
// It should store either:
// - float gpa
// - int research_hours
typedef union {
float gpa;
int research_hours;
} AcademicInfo;
/* ================= STRUCT ================= */
// TODO: Define a struct called Student
// It should contain:
// - name (string)
// - age (int)
// - program (enum ProgramType)
// - info (union AcademicInfo)
typedef struct {
    char name[100];
    int age;
    ProgramType program;
    AcademicInfo Info;


} Student;
/* ================= FUNCTION PROTOTYPES ================= */
void inputStudent(Student *s);
void displayStudent(Student s);
/* ================= MAIN FUNCTION ================= */
int main() {
int n;
printf("Enter number of students: ");
scanf("%d", &n);
// TODO: Dynamically allocate memory for n students
Student *students = (Student *)malloc(n * sizeof(Student));
// TODO: Check if memory allocation failed
// TODO: Loop to input student data
for (int i = 0; i < n; i++) {
generated by "Markdown to PDF Fast Converter" 👉 https://dub.sh/79wTuSy
printf("\n--- Student %d ---\n", i + 1);
inputStudent(&students[i]);
}
// TODO: Display all student records
printf("\n===== Student Records =====\n");
for (int i = 0; i < n; i++) {
displayStudent(students[i]);
}
// TODO: Free allocated memory
return 0;
}
/* ================= INPUT FUNCTION ================= */
void inputStudent(Student *s) {
// TODO: Input name
printf("Enter name: ");
// Hint: use scanf(" %[^\n]", ...)
/
// TODO: Based on program:
// If Undergraduate → input GPA
// If Postgraduate → input research hours
}
/* ================= DISPLAY FUNCTION ================= */
void displayStudent(Student s) {
printf("\nName: %s\n", s.name);
printf("Age: %d\n", s.age);
// TODO: Display program type
// TODO: Display either GPA or research hours
}